# .streamlit/secrets.toml

# 1. Google Gemini API Key
# Get this from your Google AI Studio dashboard.
GEMINI_API_KEY = "AIzaSyBfdXelTH__x7ZsVEp9D31p5Dm_mz1kADE"


# 2. Supabase Project Credentials
# Find these in your Supabase project under Settings > API.
SUPABASE_URL = "https://tfchhmpotpmlahrweiwt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmY2hobXBvdHBtbGFocndlaXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MTQwOTgsImV4cCI6MjA4NjI5MDA5OH0._Rn_Ad7oYfZnIsV-G20VKXL_zLzzc0Mh5H7qRHrRhi4"

# 3. Email Sending Credentials
# Use the email address you want to send reports from.
# The password MUST be a 16-digit App Password, not your regular email password.
[email_credentials]
address = "sundarvikas01@gmail.com"
password = "rxkkennktixothdy"

[virustoal]
api_keys = ["d686ce1c961994b8361c0325bb827bc54f1072c0c703b5e56da0482728384246",
"267f0eea0f6a005db1f443516e6c8db1a290a541a88e200ced98efc0cce4e3cf",
"061ab8204850d0cf60ab58fc6d4167955ccd23e4f1a365877e392ecfae453d11"
]
